# Generated by Django 4.1.4 on 2024-03-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_orderitem_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cart', 'Cart'), ('Order', 'Order'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='Cart', max_length=200, null=True),
        ),
    ]
