# Generated by Django 4.1.4 on 2024-03-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_order_status_wishlist_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='available_quantity',
        ),
    ]
